### ISSUE TITLE
Possible error in evaluation metric

### ISSUE THREAD

**Issue by axeber01** [partha2409/DCASE2024_seld_baseline#1] opened 2024-05-28 14:34 UTC
@polarch 

Why are the macro-averaged angular error and distance errors only calculated over classes with F-scores > 0? 

https://github.com/partha2409/DCASE2024_seld_baseline/blob/f4f73ad92ebc92cbf9664c0bc6454f07b7b1a01b/SELD_evaluation_metrics.py#L322-L325

This is not aligned with the metrics defined [here](https://dcase.community/challenge2024/task-audio-and-audiovisual-sound-event-localization-and-detection-with-source-distance-estimation#metrics]), where the errors are supposed to be averaged over correct classifications without any thresholds. Since a threshold of 20 degrees is used to calculate the F-score, the current implementation will exclude correctly classified events with large angular error from the average. Another consequence is that if you change the angular threshold, it will change the average angular error, which it should not.

For some of my models, averaging over only classes with F >0 decreases the angular error with almost 10 degrees compared to averaging over all classes, whereas for other models it does not change at all. This makes it difficult to evaluate which model is better. So how will they be evaluated in the challenge?

**Comment by partha2409** [comment] 2024-05-29 13:18
@axeber01

You are correct. It is a bug. By design, we decided to have localization errors independent of the spatially thresholded F1. Currently, the mean DOAE/SDE is computed correctly (over all the true positives), but at the averaging stage over classes, the final DOAE is (as you note) averaged over classes with a non-zero F1_thresh. This is a bug from our side while implementing the evaluation with a new codebase.

This has been FIXED now.

**Comment by dberghi** [comment] 2024-05-29 14:16
Please, correct me if I am wrong, but I believe this was originally implemented to avoid the 180deg penalization for undetected classes. Since STARSS23 includes rarely encountered classes such as "knock", it is possible for these classes to go undetected.  
This is in the challenge's description: "This year's localization error (DOAE) does not penalize with 180° in undetected classes/events."

However, as @axeber01 pointed out, the macro-average check should not be conducted on the F1 score as this is thresholded: an event might be detected but with a DOAE>20deg, leaving its F1=0. 
Instead, the check should verify whether there exists at least one unthresholded true positive in that class.

**Comment by partha2409** [comment] 2024-05-29 14:44
@dberghi

You are absolutely right. The original intention was to prevent the 180° penalization. Unfortunately, I applied it to the thresholded F-score resulting in the bug.

Please note that "This year's localization error (DOAE) does not penalize with 180° in undetected classes/events." is still very much valid. We indeed check whether there exists at least one unthresholded true positive in a class. If it does not exist, we assign NaN to the angular error and calculate np.nanmean in the macro averaging step. Hence, they are not penalized with 180°.

**Comment by polarch** [comment] 2024-05-29 14:45
Hi @dberghi and @axeber01,  

This is correct - the averaging avoids undetected classes to avoid over-penalising with the 180deg (the earlier strategy, and incompatible with SDE this year). And you're also correct on "_the macro-average check should not be conducted on the F1 score as this is thresholded_", it should be instead conducted on the "unthresholded" F1 (a direct pure-detection F1), and not the thresholded one - that is the bug that is fixed now.

**Closed as completed** 2024-06-12 11:04 UTC
